### PR TITLE
fix meta translation

### LINKED ISSUE #339: wrong language meta description on /en
https://dwhdelft.nl/en/  has the `meta[name="description"]` text in Dutch

### PR DESCRIPTION
**Pull request by vanadie**
Fixes #339

### CODE REVIEW

**Comment by vanadie** [comment]
Third time's the charm

File: assets/lang/en.js [hunk 1]
```diff
@@ -1,4 +1,14 @@
 export default {
+  meta: {
+    home: {
+      title: 'DWH - LGBT+ association Delft',
+      description:
+        'DWH is the independent LGBT+ association of Delft and surroundings.' +
+        " We're two things, a meeting place for LGBT+ people and their" +
+        ' friends and a group that actively pushes for greater LGBT+' +
+        ' rights and acceptance.',
```
Comment (casperboone) [inline assets/lang/en.js:9]:
```suggestion
      description:
        `DWH is the independent LGBT+ association of Delft and surroundings.
        We're two things, a meeting place for LGBT+ people and their
        friends and a group that actively pushes for greater LGBT+
        rights and acceptance.`,
```
I prefer something like this for a multiline string (not sure if this _exact_ suggestion will pass the linter): less noise and no fiddling with the quote type.
